### ISSUE TITLE
Question on addition of libraries

### ISSUE THREAD

**Issue by lhackel-tub** [geoaigroup/awesome-vision-language-models-for-earth-observation#3]
Hello,

I would like to add a python [package](https://github.com/lhackel-tub/ConfigILM) that was created in our group for Image-Language-Models with a strong focus on remote sensing applications. However, I am unsure how to add it. I guess it should be a new table similar to the one for datasets?

**Comment by aghand0ur** [comment]
thank you @lhackel-tub for pointing this out..
I have added a reference to your ConfigILB library here:
https://github.com/geoaigroup/awesome-vision-language-models-for-earth-observation#related-repositories--libraries
